#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

//#define LPM_CONF_MAX_PM 1


#define IEEE802154_CONF_PANID            0xABCD
#define IEEE802154_CONF_DEFAULT_CHANNEL      25
#define RPL_CONF_DEFAULT_LEAF_ONLY 1
//#define LOG_CONF_LEVEL_EDHOC LOG_LEVEL_DBG
#define LOG_CONF_LEVEL_RPL LOG_LEVEL_DBG
#define LOG_CONF_LEVEL_IPV6 LOG_LEVEL_DBG
#define LOG_CONF_LEVEL_MAC LOG_LEVEL_DBG
#define LOG_CONF_LEVEL_FRAMER LOG_LEVEL_DBG
//#define LOG_CONF_LEVEL_COAP LOG_LEVEL_DBG
/*#define LOG_CONF_LEVEL_TCPIP LOG_LEVEL_DBG */
/*#define LOG_CONF_LEVEL_IPV6 LOG_LEVEL_DBG */


//#define WATCHDOG_CONF_ENABLE 0x00000000
//#define SYS_CTRL_CONF_SYS_DIV SYS_CTRL_CLOCK_CTRL_SYS_DIV_32MHZ

#endif /* PROJECT_CONF_H_ */

/** @} */
